name: .NET Core

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1.0.2
      with:
        dotnet-version: 3.0.100
    - name: Build with dotnet
      env: # Or as an environment variable
        TWITTER_ID: ${{ secrets.TWITTER_ID }}
        TWITTER_PASSWD: ${{ secrets.TWITTER_PASSWD}}
        MAIL: ${{ secrets.MAIL}}
      run: |
        wget https://chromedriver.storage.googleapis.com/80.0.3987.106/chromedriver_linux64.zip
        unzip chromedriver_linux64.zip
        wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
        sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
        sudo apt-get update
        sudo apt-get install google-chrome-stable xvfb
        dotnet add package canopy --version 2.1.0
        dotnet add package Selenium.WebDriver.ChromeDriver
        DISPLAY=:1 xvfb-run dotnet run
        cat Liked.json



